# Generated by Django 4.2.7 on 2023-11-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/None/noimg.jpg', upload_to='Images/'),
        ),
    ]
